### ISSUE TITLE
Cleanup of files in /tmp

### ISSUE THREAD

**Issue by MachineGunnur** [guental/sigchk#1]
Is is possible to cleanup the temporary .zip files that are left over?  sigchk_xxy123.zip

**Comment by guental** [comment]
Yes. Please use `rm -f -- sigchk_*.zip` for old. Tested, reproducible, the issue was:
`tmp_zip=$( mkzip )` is forking a subshell in the `test_zip` function and setting a `trap` on exit. `rm` expected the `rc` variable which exists only in the subshell and died: As the result, files were left out. Putting a result of `tmp_zip` isntide a global array of `test_zip` is a solution to resolve the problem.
